automatic pitch
Fedoraware/Fedoraware pull request #631
Opened 2022-08-10 18:09 UTC by NitroTF2

automatic pitch changer, might add some edge logic to it later.

2022-08-10 18:10 UTC, NitroTF2 commented
> kid named poo

fuck you

2022-08-10 18:15 UTC, lnx00 requested changes
The if statements are invalid and do not actually compare the class numbers. This means that most values will always be true.

2022-08-10 18:20 UTC, johnathon-walnut commented on Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp
> +		if (pLocal->GetClassNum() == CLASS_SCOUT && CLASS_SPY && CLASS_PYRO) // no neeed to change their pitch
Are you retarded

2022-08-10 18:20 UTC, johnathon-walnut commented on Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp
> +			if (pLocal->GetClassNum() == CLASS_HEAVY && CLASS_DEMOMAN && CLASS_SOLDIER && CLASS_ENGINEER && CLASS_MEDIC && CLASS_SNIPER && pWeapon->GetSlot() == SLOT_PRIMARY) {
This doesn't work

2022-08-10 18:20 UTC, johnathon-walnut commented on Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp
> +			if (pLocal->GetClassNum() == CLASS_HEAVY && CLASS_DEMOMAN && CLASS_SOLDIER && CLASS_ENGINEER && CLASS_MEDIC && CLASS_SNIPER && pWeapon->GetSlot() == SLOT_SECONDARY)
Why are you like this

2022-08-10 18:20 UTC, johnathon-walnut commented on Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp
> +			if (pLocal->GetClassNum() == CLASS_HEAVY && CLASS_DEMOMAN && CLASS_SOLDIER && CLASS_ENGINEER && CLASS_MEDIC && CLASS_SNIPER && pWeapon->GetSlot() == SLOT_MELEE)
This still doesn't work

2022-08-10 18:21 UTC, johnathon-walnut commented on Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp
> +			if (pLocal->GetClassNum() == CLASS_MEDIC && pWeapon->GetSlot() == SLOT_SECONDARY && (speed < 2.0f)) // if you move it changes pitch
This one actually does good job

2022-08-10 18:21 UTC, NitroTF2 commented on Fedoraware/TeamFortress2/TeamFortress2/Features/AntiHack/AntiAim.cpp
> +			if (pLocal->GetClassNum() == CLASS_HEAVY && CLASS_DEMOMAN && CLASS_SOLDIER && CLASS_ENGINEER && CLASS_MEDIC && CLASS_SNIPER && pWeapon->GetSlot() == SLOT_PRIMARY) {
FIXING

2022-08-10 18:21 UTC, NitroTF2 commented
FIXING IT

2022-08-10 18:38 UTC, lnx00 commented
wtf

2022-08-10 18:39 UTC, lnx00 commented
https://en.wikipedia.org/wiki/Boolean_algebra

2022-08-10 18:49 UTC, johnathon-walnut commented
@NitroTF2 can you check to make sure this is the same logic you initially proposed

2022-08-10 19:22 UTC, NitroTF2 commented
> @NitroTF2 can you check to make sure this is the same logic you initially proposed

yes if the vel speed is above 2 then change it

2022-08-10 19:34 UTC, NitroTF2 commented
but you don't change on secondary slot or melee...

2022-08-10 20:01 UTC, johnathon-walnut commented
neither do you, since the angles are the same as everything else why check?

2022-08-10 20:08 UTC, NitroTF2 commented
> neither do you, since the angles are the same as everything else why check?

cuz works best to medic and i do change angle

Uploading 2022-08-10 23-08-30.mp4…

s

2022-08-10 20:12 UTC, NitroTF2 commented
@johnathon-walnut

2022-08-10 20:13 UTC, johnathon-walnut commented
> > neither do you, since the angles are the same as everything else why check?
> 
> cuz works best to medic and I do change angle
> 
> based on my logics
> 2022-08-10.23-08-30.mp4

tard, my point is that there's no point checking if not primary because it still sets it to 89 on both

2022-08-10 20:18 UTC, NitroTF2 commented
> > > neither do you, since the angles are the same as everything else why check?
> > 
> > 
> > cuz works best to medic and I do change angle
> > based on my logics
> > 2022-08-10.23-08-30.mp4
> 
> tard, my point is that there's no point checking if not primary because it still sets it to 89 on both

sheeeeit my bad i am high

well it has my logic so it is good to good

2022-08-11 04:40 UTC, xxmyn commented
ouch

2022-08-12 10:12 UTC, merged